//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public int User_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int Employee_ID { get; set; }
        public int Project_ID { get; set; }
        public int Task_ID { get; set; }

        public virtual ProjectTable ProjectTable { get; set; }
        public virtual TaskTable TaskTable { get; set; }
    }
}
